config/routes.rb
Cgdv::Application.routes.draw do
	
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :donations

  resources :activity_reports do
    resources :comments, :only => [:new, :edit, :update, :create, :destroy]
  end

  devise_for :users, :path_prefix => 'd',:controllers => { :registrations => "registrations" }
  resources :users do
  member do
  	  get 'image'
  	end	
  end
  
  resources :timereports
  resources :vol_times

  resources :addresses do
    get :autocomplete_catestado_estado, :on => :collection
  end
  
  resources :donors do
    resources :telephones, :addresses, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  resources :notes do
  	member do
  	  get 'print', 'image'
  	end
    resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end
  end
  
  resources :attachments do
  	member do
  	  get 'image'
  	end
  end
  
  resources :patients do
    member do
      get 'print', 'notas'
    end
  	resources :addresses, :telephones, :emails, :derechohabientes, :apoyos, :tratamientos, :comments, :diagnosticos, :refclinicas, :houses, :socioecos, :family_members, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  	
  	resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end 
  
  	
	end

  resources :volunteers do
  	member do
  	  get 'trep', 'image'
  	end
    resources :addresses, :telephones, :emails, :comments, :addinfos, :subprograms, :diagnosticos, :dailyschedules, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :providers do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :contacts do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  root :to => "pages#home"
  match '/times', :to => "pages#times"

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :folio, :adeudo, :acuenta, :restan, :subtotal, :total, :fecha, :patient_id, :elements_attributes

  before_save :check_status
  
  belongs_to :patient
  has_many :elements, :dependent => :destroy
  has_many :attachments, :as => :attachable, :dependent => :destroy
  
  accepts_nested_attributes_for :elements, :allow_destroy => true

  validates :patient_id, :presence => true
  validates :folio, :presence => true,:length => { :maximum => 20},
  			:numericality => true, :uniqueness => true
  validates :adeudo, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :acuenta, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :restan, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :subtotal, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :total, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :fecha, :presence => true
  
  protected
    def check_status
      @patient = Patient.find(patient_id) 
      if @patient.status != 1
      	errors[:patient_id] << I18n.t('note.error_pat')	
        false
      end
	end  
end


# == Schema Information
#
# Table name: notes
#
#  id         :integer         not null, primary key
#  folio      :integer
#  adeudo     :decimal(22, 2)
#  acuenta    :decimal(22, 2)
#  restan     :decimal(22, 2)
#  subtotal   :decimal(22, 2)
#  total      :decimal(22, 2)
#  fecha      :date
#  patient_id :integer
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  load_and_authorize_resource	
  before_filter :authenticate_user!
      
  def index
  	@search = Note.search(params[:q])
  	@title = t('note.index')
  	@notes = @search.result.order('folio DESC').page(params[:page]).per(10)
  end
  
  def show
    @note = Note.find(params[:id])
    @attachments = @note.attachments
  end
  
  def print 
    @note = Note.find(params[:id])
  	render :layout => false 
  end

  def image
  	@note = Note.find(params[:id])
    send_file "#{Rails.root}#{@note.attachment_url}",:disposition => 'inline', :type=>"application/jpg", :x_sendfile=>true
  end
	
  def new
  	@note = Note.new
  	@note.patient_id = 0
    @folio = notefolio
  	@title = t('helpers.submit.create', :model => Note.to_s)
  	6.times { @note.elements.build }
  	#JSON Data
    @adeudo = getadeudo
    @name = getname
  	respond_to do |format|
  	  format.html
      format.json{ render :json => [@adeudo,@name] }
    end
  end
  
  def edit
    @note = Note.find(params[:id])
    @folio = @note.folio
    @title = t('helpers.submit.update', :model => Note.to_s)
  end
  
  def create
  	@note = Note.new(params[:note])
  	if @note.save
  	  @note = calculos(@note)
  	  if @note.save	
  	    flash[:success] = t('flash.success.create', :model => Note.to_s)
  	    redirect_to @note
  	  else
  	    @title = "New Note"
  	    @folio = notefolio
  	    render 'new'
  	  end
  	else
  	  @title = "New Note"
  	  @folio = notefolio
  	  render 'new'
  	end
  end
  
  def update
    @note = Note.find(params[:id])
    @folio = @note.folio
    if @note.update_attributes(params[:note])
      @note = calculos(@note)
      if @note.save	
        flash[:success] = t('flash.success.edit', :model => Note.to_s)
        redirect_to @note
      else
        @title = t('helpers.submit.create', :model => Note.to_s)
        render 'edit'
      end
    else
      @title = t('helpers.submit.create', :model => Note.to_s)
      render 'edit'
    end
  end
  
  def destroy
    Note.find(params[:id]).destroy
    flash[:success] = t('flash.success.destroy', :model => Note.to_s)
    redirect_to notes_path
  end
  
  private
  
    def notefolio
      if Note.last == nil
  	    @folio = 1
  	  else
  	    @folio = Note.last.folio + 1
  	  end	
    end
    
    def getadeudo
      if !params[:id].nil?
  	    Patient.find(params[:id]).notes.last.nil? ? @adeudo = 0 : @adeudo = Patient.find(params[:id]).notes.last.restan
  	  end
    end
    
    def getname
      if !params[:id].nil?
  	    Patient.find(params[:id]).name.nil? ? @name = "" : @name = Patient.find(params[:id]).name
  	  end
    end

	def calculos(note)
	  sub = 0
	  for element in note.elements
	    sub += (element.cuota * element.cantidad)
	  end
	  note.subtotal = sub
	  note.total = note.subtotal + note.adeudo
	  note.restan = note.total - note.acuenta  
	  return note
	end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_element_fields.html.erb
<tr>
  <td><%= f.text_field :codigo, :size => 5 %></td>
  <td><%= f.text_field :descripcion, :size => 30 %></td>
  <td><%= f.text_field :cuota, :size => 3 %></td>
  <td><%= f.text_field :cantidad, :size => 3 %></td>
  <td id=<%= "'subtotal_#{index}'" %>></td>	 
  <td><%= f.label :_destroy, t('note.del') %></td>
  <td><%= f.check_box :_destroy %></td>
</tr>

app/views/notes/_note.html.erb
<tr>
  <td><%= link_to "#{note.folio}", note %></td>
  <td><%= link_to "#{t('patient.cgdvcode')}: #{cgdvcode(note)}", note %></td>
  <td><%= l note.fecha %></td>
  <% if can? :delete, @note %>
  <td><%= link_to t('helpers.delete.msg'), note, :method => :delete, :confirm => t('helpers.delete.conf'), :title => "#{t('helpers.delete.msg')} #{note.folio}" %></td>
  <% end %>
  <td><%= link_to t('helpers.print'), print_note_path(note) %></td>
</tr>


app/views/notes/_notebody.html.erb
<tr>
  <td><strong><%= t('note.codigo') %></strong></td>
  <td><strong><%= t('note.descripcion') %></strong></td>
  <td><strong><%= t('note.cuota') %></strong></td>
  <td><strong><%= t('note.cantidad') %></strong></td>
  <td><strong>Subtotal</strong></td>
</tr>
<% for element in @note.elements %>  
<tr>
  <td><%= element.codigo %></td>
  <td><%= element.descripcion %></td>
  <td><%= number_to_currency(element.cuota) %></td>
  <td><%= element.cantidad %></td>
  <td><%= number_to_currency(element.cuota*element.cantidad) %></td>
</tr>
<% end %>  
<tr>
  <td><strong><%= t('note.subtotal') %></strong></td>
  <td><strong><%= t('note.adeudo') %></strong></td>
  <td><strong><%= t('note.total') %></strong></td>
  <td><strong><%= t('note.acuenta') %></strong></td>
  <td><strong><%= t('note.restan') %></strong></td>
</tr>
<tr>
  <td><%= number_to_currency(@note.subtotal) %></td>
  <td><%= number_to_currency(@note.adeudo) %></td>
  <td><%= number_to_currency(@note.total) %></td>
  <td><%= number_to_currency(@note.acuenta) %></td>
  <td><%= number_to_currency(@note.restan) %></td>
</tr>

app/views/notes/_notebodyprint.html.erb
<tr align="left">
  <th width="129" align="center"><%= t('patient.name') %>:</th>
  <td width="466" align="center"><%= name(@note) %></td>
  <th width="117" align="center" >Registro</th>
  <td width="98" align="center"><%= cgdvcode(@note) %></td>
</tr>
<tr align="center">
  <td><strong><%= t('note.codigo') %></strong></td>
  <td><strong><%= t('note.descripcion') %></strong></td>
  <td><strong><%= t('note.cuota') %></strong></td>
  <td><strong><%= t('note.cantidad') %></strong></td>
</tr>
<% for element in @note.elements %>  
<tr>
  <td align="center"><%= element.codigo %></td>
  <td align="left"><%= element.descripcion %></td>
  <td align="center"><%= number_to_currency(element.cuota) %></td>
  <td align="center"><%= element.cantidad %></td>
</tr>
<% end %>
<tr align="center">
  <th CELLPADDING=10 colspan="3" align="right"><%= t('note.subtotal') %></th>
  <td><%= number_to_currency(@note.subtotal) %></td>
</tr>

app/views/notes/_noteheaderprint.html.erb
<tr>
  <th align="left" class="nota_title">Con Ganas de Vivir A.C.</th>
  <th align="right"><%= t('note.fecha') %>: </th>
  <td align="left"><%= l @note.fecha, :format => :long %></td>
  <th align="right" class="nota_title"><%= t('note.folio') %></th>
  <td align="left" class="nota_title"><u><strong><%= @note.folio %></strong></u></td>
</tr>

app/views/notes/_noteinfo.html.erb
<table>
  <tr>
  	<td><strong><%= t('patient.cgdvcode') %>:</strong> <%= cgdvcode(@note) %></td>
    <td><strong><%= t('patient.name') %>:</strong> <%= name(@note) %></td>
  </tr>
  <tr>
    <td><strong><%= t('note.folio') %>:</strong> <%= @note.folio %></td>
    <td><strong><%= t('note.fecha') %>:</strong> <%= l @note.fecha, :format => :long %></td>
  </tr>
</table>
<table>
<%= render 'notebody' %>
</table>

app/views/notes/_noteprint.html.erb
<table class="nota" border="0" width="90%">
<%= render 'noteheaderprint' %>
</table>
<table border="0" width="100%">
  <tr>
    <td align="left" class="nota_datos">
    Con Ganas de Vivir A.C. RFC: GVI-020604-P61, Av. Universidad 474 Col. Vertiz Narvarte, 
    Benito Juárez México D.F., C.P. 03600 Tels. 5543-1022 y 5543-3192.
    </td>
  </tr>
</table>
<table class="nota" border="1" width="100%" frame="box" rules="all">
<%= render 'notebodyprint' %>
</table>
<table class="nota" border="1" width="100%" frame="box" rules="all">
<%= render 'notetotalsprint' %>
</table>
<table class="nota nota_leyenda" border="0" width="100%">
  <tr>
    <td align="left">
    Recibí(mos) los apoyos descritos anteriormente por parte de Con Ganas de Vivir A.C., aceptando
    lo establecido en el reglamento de la Asociación, y reconociendo el monto por concepto de cuota
    de recuperación que aparece en la casilla de total de este documento.
    </td>
  </tr>
</table>

app/views/notes/_notetotalsprint.html.erb
<tr>
  <th width="149" align="center"><%= t('note.subtotal') %></th>
  <th width="242" align="center"><%= t('note.adeudo') %></th>
  <th width="242" align="center"><%= t('note.total') %></th>
  <th width="182" align="center"><%= t('note.acuenta') %></th>
  <th width="175" align="center"><%= t('note.restan') %></th>
</tr>
<tr align="center">
  <td><%= number_to_currency(@note.subtotal) %></td>
  <td><%= number_to_currency(@note.adeudo) %></td>
  <td><%= number_to_currency(@note.total) %></td>
  <td><%= number_to_currency(@note.acuenta) %></td>
  <td><%= number_to_currency(@note.restan) %></td>
</tr>
<tr>
 <th height="35" align="right">Recibí</th>
 <td height="35" colspan="4"></td>
</tr>

app/views/notes/_patient.html.erb
<%= search_form_for @search, :url => notas_patient_path(patient), :html => {:method => :get} do |f| %>
  
  <h6><%= t('search.title') %></h6>	
  <%= f.label :folio_cont, t('note.folio') %>
  <%= f.text_field :folio_eq %>
  <%= f.submit t('helpers.search') %><br /><br />
<% end %>

<strong><%= t('search.sort') %>	</strong>

<%= paginate @notes %>

<table>
	<tr>
	  <td><strong><%= sort_link @search, :folio, t('note.folio') %></strong></td>
	  <td><strong><%= t('patient.cgdvcode') %></strong></td>
	  <td><strong><%= sort_link @search, :created_at, t('all.created_at') %></strong></td>
    </tr>
	<%= render @notes %>
</table>


<%= paginate @notes %>

app/views/notes/edit.html.erb
<h1><%= t('helpers.submit.update', :model => Note.to_s) %></h1>
<p>
En las notas aparecen los 6 campos por defecto. Si hay campos que no se van a utilizar, para que no se generen errores se debe de seleccionar la opción de <strong>¿Eliminar?</strong>. No los rellenes con '0' o 'xxx'.<br />
</p>
<%= nested_form_for(@note) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit t('helpers.edit') %>
  </div>
<% end %>

app/views/notes/index.html.erb
<h1><%= t('note.index') %></h1>
<h6><%= link_to t('helpers.submit.create', :model => "Nueva Nota"), new_note_path %></h6><br />

<%= search_form_for @search, :url => notes_path, :html => {:method => :get} do |f| %>
  
  <h6><%= t('search.title') %></h6>	
  <%= f.label :folio_eq, t('note.folio') %>
  <%= f.text_field :folio_eq, :size => 3 %>
  <%= f.label :cgdvcode_eq, t('search.cgdvcode') %>
  <%= f.text_field :patient_cgdvcode_eq, :size => 3 %>
  <%= f.label :folio_cont, t('search.name') %>
  <%= f.text_field :patient_name_cont %>
  <%= f.submit t('helpers.search') %><br /><br />
<% end %>

<strong><%= t('search.sort') %>	</strong>

<%= paginate @notes %>

<table>
	<tr>
	  <td><strong><%= sort_link @search, :folio, t('note.folio'), :default_order => :desc %></strong></td>
	  <td><strong><%= t('patient.cgdvcode') %></strong></td>
	  <td><strong><%= sort_link @search, :created_at, t('all.created_at'), :default_order => :desc %></strong></td>
    </tr>
	<%= render @notes %>
</table>


<%= paginate @notes %>

app/views/notes/new.html.erb
<h1><%= t('helpers.submit.create', :model => Note.to_s) %></h1>
<p>
En las notas aparecen los 6 campos por defecto. Si hay campos que no se van a utilizar, para que no se generen errores se debe de seleccionar la opción de <strong>¿Eliminar?</strong>. No los rellenes con '0' o 'xxx'.<br />
</p>
<%= nested_form_for(@note) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit t('helpers.create'), :confirm => "¿El Registro CGDV del Paciente es el correcto?" %>
  </div>
<% end %>

app/views/notes/print.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'customprint', :media => "screen, print, projection" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="wrap">
      <div id="header" align="center">
        <%= render 'noteprint' %><hr />
        <%= render 'noteprint' %><hr />
        <%= render 'noteprint' %>
      </div>
    </div>
  </body>
</html>

app/views/notes/show.html.erb
<h1><%= t('note.title') %>: <%= @note.folio %></h1>
<strong><%= link_to t('helpers.submit.update', :model => "Nota"), edit_note_path(@note) %></strong> | 
<strong><%= link_to t('helpers.print'), print_note_path(@note) %></strong><br /><br />
<table>
<%= render 'noteinfo' %>
<%= render 'attachments/attachments', :model => @note %>
</table>