config/routes.rb
Cgdv::Application.routes.draw do
	
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :donations

  resources :activity_reports do
    resources :comments, :only => [:new, :edit, :update, :create, :destroy]
  end

  devise_for :users, :path_prefix => 'd',:controllers => { :registrations => "registrations" }
  resources :users do
  member do
  	  get 'image'
  	end	
  end
  
  resources :timereports
  resources :vol_times

  resources :addresses do
    get :autocomplete_catestado_estado, :on => :collection
  end
  
  resources :donors do
    resources :telephones, :addresses, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  resources :notes do
  	member do
  	  get 'print', 'image'
  	end
    resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end
  end
  
  resources :attachments do
  	member do
  	  get 'image'
  	end
  end
  
  resources :patients do
    member do
      get 'print', 'notas'
    end
  	resources :addresses, :telephones, :emails, :derechohabientes, :apoyos, :tratamientos, :comments, :diagnosticos, :refclinicas, :houses, :socioecos, :family_members, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  	
  	resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end 
  
  	
	end

  resources :volunteers do
  	member do
  	  get 'trep', 'image'
  	end
    resources :addresses, :telephones, :emails, :comments, :addinfos, :subprograms, :diagnosticos, :dailyschedules, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :providers do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :contacts do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  root :to => "pages#home"
  match '/times', :to => "pages#times"

end

app/models/activity_report.rb
class ActivityReport < ActiveRecord::Base
  attr_accessible :reporte, :volunteer_id
  
  belongs_to :volunteer
  
  before_create :get_week
  before_create :set_week

  has_many :comments, :as => :commentable, :dependent => :destroy

  validates :volunteer_id, :presence => true
  #Para contar que tenga minimo 1 y maximo 750 palabras
  validates :reporte, :presence => true, :length => {
    :minimum   => 1,
    :maximum   => 750,
    :tokenizer => lambda { |str| str.scan(/\w+/) }
  }
  
  private

	def get_week
	  week = Time.now.strftime("%W").to_i
	  wday = Time.now.wday
	  week = wday <= 3 ?  week - 1 : week
	  	
	  registro = ActivityReport.find(:all, :conditions => {:volunteer_id => self.volunteer_id, :semana => week})
	  if !registro.empty?
	   errors[:semana] = ": Ya existe un registro de esta Semana"
	   return false
  	  end
	end
	
	def set_week
	  week = Time.now.strftime("%W").to_i
	  wday = Time.now.wday
	  if wday <= 3
	    self.semana = week - 1
	  else
	    self.semana = week
	  end
	end
  
end


# == Schema Information
#
# Table name: activity_reports
#
#  id           :integer         not null, primary key
#  reporte      :text
#  semana       :integer
#  volunteer_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/activity_reports_controller.rb
class ActivityReportsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!	

  def index
  	@activity_reports = []
  	if !current_user.volunteer_id.nil?
  	  if current_user.admin?
  	  	@search = ActivityReport.search(params[:q])
  	  	@activity_reports = @search.result.order('semana DESC').page(params[:page]).per(10)
  	  else
  	  	@search = ActivityReport.where(:volunteer_id => current_user.volunteer_id).search(params[:q])
  	  	@activity_reports = @search.result.order('semana DESC').page(params[:page]).per(10)
  	  	if @activity_reports.nil?
  	  	  @activity_reports = []
  	  	end
  	  end
  	end
    @title = "Reportes de Actividades"
  end

  def show
    @activity_report = ActivityReport.find(params[:id])
    @comments = @activity_report.comments
  end

  def new
    @activity_report = ActivityReport.new
    @activity_report.volunteer_id = getvolunteerid
    @title = "Reportes de Actividades"
  end

  def create
    @activity_report = ActivityReport.new(params[:activity_report])
    @activity_report.volunteer_id = getvolunteerid
    puts @activity_report
    if @activity_report.save
      flash[:success] = t('flash.success.create', :model => "Reportes de Actividades")
      redirect_to @activity_report
    else
      render :action => 'new'
    end
  end

  def edit
    @activity_report = ActivityReport.find(params[:id])
	@title = "Reportes de Actividades"
  end

  def update
    @activity_report = ActivityReport.find(params[:id])
    if @activity_report.update_attributes(params[:activity_report])
      flash[:success] = t('flash.success.edit', :model => "Reportes de Actividades")
      redirect_to @activity_report
    else
      render :action => 'edit'
    end
  end

  def destroy
    @activity_report = ActivityReport.find(params[:id])
    @activity_report.destroy
    flash[:success] = t('flash.success.destroy', :model => "Reportes de Actividades")
    redirect_to activity_reports_url
  end
  
  private
  
    def getvolunteerid
      id = !current_user.volunteer_id.nil? ? current_user.volunteer_id : nil
      return id
    end
end

app/helpers/activity_reports_helper.rb
module ActivityReportsHelper
end

app/views/activity_reports/_activity_report.html.erb
<tr>
  <td><%= link_to activity_report.volunteer.cgdvcode, activity_report.volunteer %></td>
  <td><%= link_to "Semana #{activity_report.semana}", activity_report %></td>
  <td><%= link_to l(activity_report.created_at, :format => :rep), activity_report %></td>
  <td><%= link_to truncate(activity_report.reporte, :length => 25), activity_report %>
  <% if can? :edit, ActivityReport %>
  <td class="smally"><%= link_to t('helpers.submit.update', :model => "Reporte"), edit_activity_report_path(activity_report) %></td>
  <% end %>
  <% if can? :destroy, ActivityReport %>
	  <td class="smally"><%= link_to t('helpers.delete.msg'), activity_report, :method => :delete, :confirm => t('helpers.delete.conf'), :title => "#{t('helpers.delete.msg')} #{activity_report.created_at}" %></td>
	  <% end %>
</tr>

app/views/activity_reports/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div>
  <%= f.label :reporte %><br />
  <%= f.text_area :reporte %>
</div>

app/views/activity_reports/edit.html.erb
<h1><%= t('helpers.submit.update', :model => "Reporte de Actividades") %></h1>
<%= nested_form_for(@activity_report) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit t('helpers.edit') %>
  </div>
<% end %>

app/views/activity_reports/index.html.erb
<h1>Reportes de Actividades</h1>

<% unless current_user.volunteer_id.nil? %>
<h6><%= link_to "Nuevo Reporte de Actividades", new_activity_report_path %></h6>
<% end %>
	
  <%= search_form_for @search, :url => activity_reports_path, :html => {:method => :get} do |f| %>
    <h6><%= t('search.title') %></h6>
    
    <% if current_user.admin? %>
    <%= f.label :cgdvcode_eq, t('patient.cgdvcode') %>
    <%= f.text_field :volunteer_cgdvcode_eq, :size => 3 %>
    <%= f.label :name_contains, t('patient.name') %>
    <%= f.text_field :volunteer_name_eq %>
    <% end %>
  
    <%= f.label :semana, "Semanas desde:" %>
    <%= f.text_field :semana_gteq, :size => 3 %>
    <%= f.label :semana, "hasta:" %>
    <%= f.text_field :semana_lteq, :size => 3 %>    
    <%= f.submit t('helpers.search') %><br /><br />
    
  <% end %>

  <%= paginate @activity_reports %>

<table>
  <tr>
    <th><%= sort_link @search, :volunteer_cgdvcode, t('patient.cgdvcode') %></th>
  	<th><%= sort_link @search, :semana, "Semanas", :default_order => :desc %></th>
    <th><%= sort_link @search, :created_at, t('all.created_at'), :default_order => :desc %></th>
    <th>Reportes</th>
  </tr>
  <%= render @activity_reports %>
</table>

  <%= paginate @activity_reports %>

app/views/activity_reports/new.html.erb
<h1><%= t('helpers.submit.create', :model => "Reporte de Actividades") %></h1>
<%= nested_form_for(@activity_report) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit t('helpers.create') %>
  </div>
<% end %>

app/views/activity_reports/show.html.erb
<h1><%= "Reporte de la Semana #{@activity_report.semana}"  %></h1>
<% if can? :edit, @activity_report %>
<%= link_to t('helpers.submit.update', :model => "Reporte"), edit_activity_report_path(@activity_report) %><br />
<% end %>
<%= link_to "Regresar a Reportes de Actividades", activity_reports_path %><br /><br />
<table>
<tr>
  <th><%= t('patient.name') %></th>
  <th><%= t('note.fecha') %></th>
</tr>
<tr>
  <td><%= @activity_report.volunteer.name %></td>
  <td><%= l(@activity_report.created_at,:format => :long) %></td>
</tr>
<tr><th colspan=2>Reporte</th></tr>
</table>
<p><%= simple_format(@activity_report.reporte) %></p>

<%= render 'comments/comments', :model => @activity_report %>

<%= link_to "Regresar a Reportes de Actividades", activity_reports_path %>