config/routes.rb
Cgdv::Application.routes.draw do
	
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :donations

  resources :activity_reports do
    resources :comments, :only => [:new, :edit, :update, :create, :destroy]
  end

  devise_for :users, :path_prefix => 'd',:controllers => { :registrations => "registrations" }
  resources :users do
  member do
  	  get 'image'
  	end	
  end
  
  resources :timereports
  resources :vol_times

  resources :addresses do
    get :autocomplete_catestado_estado, :on => :collection
  end
  
  resources :donors do
    resources :telephones, :addresses, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  resources :notes do
  	member do
  	  get 'print', 'image'
  	end
    resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end
  end
  
  resources :attachments do
  	member do
  	  get 'image'
  	end
  end
  
  resources :patients do
    member do
      get 'print', 'notas'
    end
  	resources :addresses, :telephones, :emails, :derechohabientes, :apoyos, :tratamientos, :comments, :diagnosticos, :refclinicas, :houses, :socioecos, :family_members, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  	
  	resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end 
  
  	
	end

  resources :volunteers do
  	member do
  	  get 'trep', 'image'
  	end
    resources :addresses, :telephones, :emails, :comments, :addinfos, :subprograms, :diagnosticos, :dailyschedules, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :providers do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :contacts do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  root :to => "pages#home"
  match '/times', :to => "pages#times"

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :folio, :donor_id, :frecepcion, :tipo, :monto, :transaccion, :finalidad, :motivo
  
  belongs_to :donor
  
  validates :donor_id, :presence => true
  validates :folio, :presence => true,:length => { :maximum => 20},
  			:numericality => true, :uniqueness => true
  validates :frecepcion, :presence => true
  validates :tipo, :presence => true
  validates :motivo, :presence => true
  
  TIPO = [['Efectivo',1],['Especie',2],['Transferencia',3],['Tarjeta',4],['Deposito',5],['Paypal',6],['Banxol',7],['Otro',0]]
  MOTIVO = [['Gestion',1],['Espontaneo',2],['En Memoria',3],['Campania',4],['Dedicado',5],['Otro',0]]
  
end

# == Schema Information
#
# Table name: donations
#
#  id          :integer         not null, primary key
#  folio       :integer
#  donor_id    :integer
#  frecepcion  :date
#  tipo        :integer
#  monto       :string(255)
#  transaccion :string(255)
#  finalidad   :string(255)
#  motivo      :integer
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  load_and_authorize_resource	
  before_filter :authenticate_user!
  
  def index
  	@search = Donation.search(params[:q])
  	@title = t('donation2.index')
  	@donations = @search.result.order('folio DESC').page(params[:page]).per(10)  	
  end

  def show
    @donation = Donation.find(params[:id])
    @title = t('donation2.title')
  end

  def new
    @donation = Donation.new
	@folio = getfolio
  	@title = t('helpers.submit.create', :model => Donation.to_s)
	#JSON Data
    @name = getname
  	respond_to do |format|
  	  format.html
      format.json{ render :json => [@name] }
    end
  end

  def create
    @donation = Donation.new(params[:donation])
    if @donation.save
      flash[:success] = t('flash.success.create', :model => Donation.to_s)
      redirect_to @donation
    else
      render :action => 'new'
    end
  end

  def edit
    @donation = Donation.find(params[:id])
    @folio = @donation.folio
    @title = t('helpers.submit.update', :model => Donation.to_s)
  end

  def update
    @donation = Donation.find(params[:id])
    @folio = @donation.folio
    if @donation.update_attributes(params[:donation])
      flash[:success] = t('flash.success.edit', :model => Donation.to_s)
      redirect_to @donation
    else
      render :action => 'edit'
    end
  end

  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy
    flash[:success] = t('flash.success.destroy', :model => Donation.to_s)
    redirect_to donations_url
  end
  
  private
  
    def getfolio
      if Donation.last == nil
  	    @folio = 1
  	  else
  	    @folio = Donation.last.folio + 1
  	  end	
    end
    
    def getname
      if !params[:id].nil?
  	    Donor.find(params[:id]).name.nil? ? @name = "" : @name = Donor.find(params[:id]).name
  	  end
    end
    
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<tr>
  <td><%= link_to donation.folio, donation %></td>
  <td><%= link_to donation.donor.cgdvcode, donation.donor %></td>
  <td><%= link_to l(donation.frecepcion), donation %></td>
  <td><%= link_to donation.finalidad, donation %></td>
  <% if can? :destroy, Donation %>
    <td><%= link_to t('helpers.delete.msg'), donation, :method => :delete, :confirm => t('helpers.delete.conf'), :title => "#{t('helpers.delete.msg')} #{donation.folio}" %></td>
  <% end %>
</tr>

app/views/donations/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
  <div>
    <%= f.label :folio %><br />
    <%= f.text_field :folio, :value => @folio, :size => 3 %>
  </div>
  <div>
    <%= f.label :donor_id %><br />
  	<%= f.collection_select :donor_id, Donor.order('cgdvcode'), :id, :cgdvcode %><br />
  	<%= f.label :donor_id %><br />
    <div id="donor_name"> </div><br />
  </div>
  <div>
    <%= f.label :frecepcion %><br />
    <%= f.date_select :frecepcion, :order => [:day, :month, :year], :start_year => Time.now.year - 10 %>
  </div>
  <div>
    <%= f.label :motivo %><br />
    <%= f.select :motivo, Donation::MOTIVO %>
  </div>
  <div>
    <%= f.label :tipo %><br />
    <%= f.select :tipo, Donation::TIPO %>
  </div>
  <div>
    <%= f.label :transaccion %><br />
    <%= f.text_field :transaccion, :size => 10 %>
  </div>
  <div>
    <%= f.label :monto %><br />
    <%= f.text_field :monto, :size => 10 %>
  </div>
  <div>
    <%= f.label :finalidad %><br />
    <%= f.text_field :finalidad, :size => 50 %>
  </div>

app/views/donations/edit.html.erb
<h1><%= t('helpers.submit.update', :model => Donation.to_s) %></h1>
<%= form_for(@donation) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit t('helpers.edit') %>
  </div>
<% end %>

app/views/donations/index.html.erb
<h1><%= t('donation2.index') %></h1>
<h6><%= link_to t('helpers.submit.create', :model => "Nueva Donación"), new_donation_path %></h6><br />

<%= search_form_for @search, :url => donations_path, :html => {:method => :get} do |f| %>
  
  <h6><%= t('search.title') %></h6>	
  <%= f.label :folio_cont, t('note.folio') %>
  <%= f.text_field :folio_eq, :size => 3 %>
  <%= f.label :cgdvcode_eq, t('search.cgdvcode') %>
  <%= f.text_field :donor_cgdvcode_eq, :size => 3 %>
  <%= f.label :name_cont, t('search.name') %>
  <%= f.text_field :donor_name_cont %>
  <%= f.submit t('helpers.search') %><br /><br />
<% end %>

<strong><%= t('search.sort') %>	</strong>

<%= paginate @donations %>

<table>
  <tr>
    <th><%= sort_link @search, :folio, t('note.folio'), :default_order => :desc %></th>
    <th><%= sort_link @search, :donor_cgdvcode, t('patient.cgdvcode'), :default_order => :desc %></th>
    <th><%= sort_link @search, :frecepcion, t('donation2.frecepcion'), :default_order => :desc  %></th>
    <th>Finalidad</th>
  </tr>
  <%= render @donations %>
</table>

<%= paginate @donations %>

app/views/donations/new.html.erb
<h1><%= t('helpers.submit.create', :model => Donation.to_s) %></h1>
<%= form_for(@donation) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit t('helpers.create') %>
  </div>
<% end %>

app/views/donations/show.html.erb
<h1><%= t('donation2.title') %>: <%= @donation.folio %></h1>
<strong><%= link_to t('helpers.submit.update', :model => "Donación"), edit_donation_path(@donation) %></strong><br /><br />

<p>
  <strong><%= t('patient.cgdvcode') %>:</strong>
  <%= @donation.donor.cgdvcode %>
</p>
<p>
  <strong><%= t('patient.name') %>:</strong>
  <%= @donation.donor.name %>
</p>
<p>
  <strong><%= t('donation2.frecepcion') %>:</strong>
  <%= l @donation.frecepcion, :format => :long %>
</p>
<p>
  <strong>Motivo:</strong>
  <%= donation_motivo(@donation.motivo) %>
</p>
<p>
  <strong>Tipo:</strong>
  <%= donation_tipo(@donation.tipo) %>
</p>
<p>
  <strong>Transaccion:</strong>
  <%= @donation.transaccion %>
</p>
<p>
  <strong>Monto:</strong>
  <%= @donation.monto %>
</p>
<p>
  <strong>Finalidad:</strong>
  <%= @donation.finalidad %>
</p>