config/routes.rb
Cgdv::Application.routes.draw do
	
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :donations

  resources :activity_reports do
    resources :comments, :only => [:new, :edit, :update, :create, :destroy]
  end

  devise_for :users, :path_prefix => 'd',:controllers => { :registrations => "registrations" }
  resources :users do
  member do
  	  get 'image'
  	end	
  end
  
  resources :timereports
  resources :vol_times

  resources :addresses do
    get :autocomplete_catestado_estado, :on => :collection
  end
  
  resources :donors do
    resources :telephones, :addresses, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  resources :notes do
  	member do
  	  get 'print', 'image'
  	end
    resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end
  end
  
  resources :attachments do
  	member do
  	  get 'image'
  	end
  end
  
  resources :patients do
    member do
      get 'print', 'notas'
    end
  	resources :addresses, :telephones, :emails, :derechohabientes, :apoyos, :tratamientos, :comments, :diagnosticos, :refclinicas, :houses, :socioecos, :family_members, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  	
  	resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end 
  
  	
	end

  resources :volunteers do
  	member do
  	  get 'trep', 'image'
  	end
    resources :addresses, :telephones, :emails, :comments, :addinfos, :subprograms, :diagnosticos, :dailyschedules, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :providers do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :contacts do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  root :to => "pages#home"
  match '/times', :to => "pages#times"

end

app/models/timereport.rb
class Timereport < ActiveRecord::Base
  belongs_to :volunteer
  
  attr_accessible :day, :begin, :end, :evento, :volunteer_id

  validates :day, :presence => true  
  validates :begin, :presence => true
  validates :end, :presence => true
  validates :volunteer_id, :presence => true
  
  DAYS = [['Lunes',1],['Martes',2],['Miercoles',3],['Jueves',4],['Viernes',5],['Sabado',6],['Domingo',7]]
  EVENTO = ['Eventos Especiales', 'Apoyo Intrahospitalario', 'Suenos y Deseos', 'Captacion de Fondos', 'Apoyo en Labores Administrativas', 'Grupos de Autoayuda','Sobrevivientes', 'Fugarte', 'Dia de Reyes', 'Dia del Nin@', 'Corriendo por la Vida', 'Donador de sangre y o plaquetas', 'Curso de Capacitacion Basico', 'Curso de Capacitacion A', 'Curso de Capacitacion B', 'Curso de Capacitacion C', 'Curso de Capacitacion D', 'Curso de Capacitacion Tematico', 'Otr@s']

    def tiempo
      total = self.end - self.begin
      hrs = (total/3600).to_i
  	  mins = (total/60 - hrs * 60).to_i
  	  return "#{hrs} hrs, #{mins} mins"
    end
    
    def tiempo_num
      total = self.end - self.begin
      hrs = (total/3600).to_i
  	  mins = (total/60 - hrs * 60)/100.to_i
  	  return [hrs,mins]
    end 
  
end



# == Schema Information
#
# Table name: timereports
#
#  id           :integer         not null, primary key
#  day          :date
#  begin        :time
#  end          :time
#  volunteer_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#  evento       :string(255)
#

app/controllers/timereports_controller.rb
class TimereportsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  
  def index
  	@search = Timereport.search(params[:q])
  	@title = t('header.timereport')
  	@timereports = @search.result.order('created_at DESC').page(params[:page]).per(15)
  end
  
  def show
    @timereport = Timereport.find(params[:id])
  end
	
  def new
  	@timereport = Timereport.new
  	@title = t('helpers.submit.create', :model => 'timereports.title')
  end
  
  def edit
    @timereport = Timereport.find(params[:id])
    @title = t('helpers.submit.update', :model => 'timereports.title')
  end
  
  def create
  	@timereport = Timereport.new(params[:timereport])
  	if @timereport.save	
  	  flash[:success] = t('flash.success.create', :model => 'timereports.title')
  	  redirect_to @timereport
  	else
  	  @title = t('helpers.submit.create', :model => 'timereports.title')
  	  render 'new'
  	end
  end
  
  def update
    @timereport = Timereport.find(params[:id])
    if @timereport.update_attributes(params[:timereport])	
      flash[:success] = t('flash.success.edit', :model => 'timereports.title')
      redirect_to @timereport
    else
      @title = t('helpers.submit.create', :model => 'timereports.title')
      render 'edit'
    end
  end
  
  def destroy
    Timereport.find(params[:id]).destroy
    flash[:success] = t('flash.success.destroy', :model => 'timereports.title')
    redirect_to timereports_path
  end

end

app/helpers/timereports_helper.rb
module TimereportsHelper
end

app/views/timereports/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

  <%= f.label :evento, t('volunteer.evento') %><br />
  <%= f.select :evento, Timereport::EVENTO %><br />

  <%= f.label :volunteer_id, t('patient.cgdvcode') %><br />	
  <%= f.collection_select :volunteer_id, Volunteer.order('cgdvcode'), :id, :cgdvcode %><br />
  
  <%= f.label :volunteer_id, t('patient.name') %><br />
  <div id="volunteer_name"> </div><br />

  <%= f.label :day, t('volunteer.day') %><br />
  <%= f.date_select :day %><br />

  <%= f.label :begin, t('volunteer.begin') %><br />
  <%= f.time_select :begin %><br />

  <%= f.label :end, t('volunteer.end') %><br />
  <%= f.time_select :end %><br />

app/views/timereports/_timereport.html.erb
<tr>
  <% if can? :read, Volunteer %>
  <td><%= link_to cgdvcode_vol(timereport), volunteer_path(timereport.volunteer_id) %></td>
  <% end %>
  <td><%= link_to l(timereport.day), timereport %></td>
  <td><%= link_to l(timereport.begin, :format => :hourmin), timereport %></td>
  <td><%= link_to l(timereport.end, :format => :hourmin), timereport %></td>
  <td><%= link_to timereport.tiempo, timereport %></td>
  <td><%= link_to timereport.evento, timereport %></td>
  <% if can? :edit, timereport %>
  <td class="smally"><%= link_to t('helpers.edit'), edit_timereport_path(timereport) %></td>
  <% end %>
  <% if can? :destroy, timereport %>
  <td class="smally">
  	<%= link_to t('helpers.delete.msg'), timereport_path(timereport), :method => :delete, :confirm => t('helpers.delete.conf'), :title => "#{t('helpers.delete.msg')} #{timereport.begin}" %>
  </td>
  <% end %>
</tr>	

app/views/timereports/_volunteer.html.erb
<%= render @timereports %>


app/views/timereports/edit.html.erb
<h1><%= t('helpers.submit.update', :model => Timereport.to_s) %></h1>
<%= nested_form_for(@timereport) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit t('helpers.edit') %>
  </div>
<% end %>

app/views/timereports/index.html.erb
<h1><%= t('timereport.title') %></h1>

<% if can? :read, VolTime %>
  <%= link_to "Añadir/Acumular Tiempo", vol_times_path %> | 
<% end %>
<% if can? :read, Timereport %>
  <%= link_to "Reportar/Restar Tiempo", timereports_path %>
<% end %>

<br /><br /><h6><%= link_to t('helpers.submit.create', :model => "Nuevo Reporte de Tiempo"), new_timereport_path %></h6><br />

<%= search_form_for @search, :url => timereports_path, :html => {:method => :get} do |f| %>
  
  <h6><%= t('search.title') %></h6>	
  <%= f.label :cgdvcode_eq, t('search.cgdvcode') %>
  <%= f.text_field :volunteer_cgdvcode_eq, :size => 3 %>
  <%= f.label :evento_cont, t('volunteer.evento') %>
  <%= f.text_field :evento_cont %>
  <%= f.label :name_cont, t('patient.name') %>
  <%= f.text_field :volunteer_name_cont %><br />
  <%= f.label :day_gteq, "Desde: " %>
  <%= f.date_select :day_gteq, :default => 1.year.ago, :start_year => Time.now.year - 20, :end_year => Time.now.year %> 
  <%= f.label :day_lteq, "Hasta: " %>
  <%= f.date_select :day_lteq, :start_year => Time.now.year - 20, :end_year => Time.now.year %>
  <%= f.submit t('helpers.search') %><br /><br />
<% end %>

<strong><%= t('search.sort') %>	</strong>

<%= paginate @timereports %>

<table>
<tr>
  <td><strong><%= sort_link @search, :volunteer_cgdvcode, t('patient.cgdvcode'), :default_order => :desc %></strong></td>	
  <td><strong><%= sort_link @search, :day, t('volunteer.day'), :default_order => :desc %></strong></td>
  <td><strong><%= sort_link @search, :begin, t('volunteer.begin'), :default_order => :desc %></strong></td>
  <td><strong><%= sort_link @search, :end, t('volunteer.end'), :default_order => :desc %></strong></td>
  <td><strong><%= t('volunteer.tiempo') %></strong></td>
  <td><strong><%= sort_link @search, :evento, t('volunteer.evento') %></strong></td>
  <td></td>
  <td></td>
</tr>
	<%= render @timereports %>
<tr>
  <td></td>
  <td></td>
  <td></td>
  <td><strong>Tiempo Total: </strong></td>
  <td><strong><%= tiempo_total(@timereports) %></strong></td>
  <td></td>
  <td></td>
  <td></td>
</tr>
</table>


<%= paginate @timereports %>

app/views/timereports/new.html.erb
<h1><%= t('helpers.submit.create', :model => Timereport.to_s) %></h1>
<%= nested_form_for(@timereport) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit t('helpers.create') %>
  </div>
<% end %>

app/views/timereports/show.html.erb
<h1><%= name_vol(@timereport) %>: <%= l @timereport.day %></h1>
<strong><%= link_to t('helpers.submit.update', :model => "Reporte de Tiempo"), edit_timereport_path(@timereport) %></strong>
<table>
<tr><td><strong><%= t('patient.cgdvcode') %>: </strong><%= cgdvcode_vol(@timereport) %></td></tr>
<tr><td><strong><%= t('volunteer.evento') %>: </strong><%= @timereport.evento %></td></tr>
<tr><td><strong><%= t('volunteer.day') %>: </strong><%= l @timereport.day %></td></tr>
<tr><td><strong><%= t('volunteer.begin') %>: </strong><%= l @timereport.begin, :format => :hourmin %></td></tr>
<tr><td><strong><%= t('volunteer.end') %>: </strong><%= l @timereport.end, :format => :hourmin %></td></tr>
<tr><td><strong><%= t('volunteer.tiempo') %>: </strong><%= @timereport.tiempo %></td>
</tr>	
</table>

<% if can? :read, Timereport %>
  <%= link_to "Regresar a Reportar/Restar Tiempo", timereports_path %>
<% end %>